### ISSUE TITLE
import cnt file in EEGLAB

### ISSUE THREAD

**Issue by saramazzini** [sccn/neuroscanio#2]
Hello to everyone!

I have a very “basic” question for you. I have been working with EEGLAB for more than a year now, but I suddenly get some erros when trying to import .cnt data.
I do not understand why this is happening or how I can fix it.
I got two different error messages for the two datasets I have tried to import: respectively, "NaN and Inf. not allowed (loadcnt() at line 557)” and “Error in function loadcnt() at line 681. Undefined function of variable ‘e’." I wanted to attach the dataset for testing purposes, but they are too big (160 MB). 

I would really appreciate any idea or suggestion on how to proceed!

Sara Mazzini

**Comment by arnodelorme** [comment]
The files are available at

https://drive.google.com/drive/folders/10cdi4NkQ9xecUmpyu4Z45-nkZmRLiiqU?usp=sharing

The problem did not arise when importing the files using File-IO, so this bug is not urgent. If you are a programmer, give it a shot.

**Comment by RiverTOREAD** [comment]
Hello to everyone,
My EEG data is recorded by Neuroscan. I import a .cnt EEG file using eeglab. After preprocessing, how can I export the date to a .cnt file rather than a .cnt file?
Thanks for your time.
Haidong

**Comment by arnodelorme** [comment]
You may use the writecnt file from the command line.
