### ISSUE TITLE
EEG 32+8 channel locations

### ISSUE THREAD

**Issue by Handerson96** [sccn/neuroscanio#3]
Hello, 

This may be a really simple question but I cannot get the HEOG, VEOG and mastoid channel locations in EEGLAB. If anyone can help with this it would be much appreciated!

**Comment by arnodelorme** [comment]
Yes, they are in the file 

eeglab/plugins/dipfit/standard_BESA/standard-10-5-cap385.elp

Best wishes,

Arno

**Comment by Handerson96** [comment]
Thank you for your reply.

I have tried this but the EX (mastoids and EOG) channels are coming up blank.

Thanks,
Hannah


Hannah Anderson

Research Assistant - Healthy Brain Ageing

I am currently working from home. If you require to get in contact via phone my number is 0412 842 635

Sunshine Coast Mind and Neuroscience - Thompson Institute, USC

handerson@usc.edu.au<mailto:mparker4@usc.edu.au> | [usc.edu.au/thompson-institute]usc.edu.au/thompson-institute

[cid:d3524f92-1334-46f4-860e-705d61fbe2ac]

I acknowledge the Traditional Custodians of the lands and waters upon which the University's campuses are located.

I acknowledge their continuing connections to country and pay my respects to Elders past, present and emerging.



University of the Sunshine Coast  l  CRICOS 01595D

________________________________

**Comment by arnodelorme** [comment]
They need to be named properly if you want to look up their location.

**Comment by Handerson96** [comment]
Hello I have opened the file but we use two HEOG flat type electrodes and two VEOG flat type electrodes, one left and right and one upper and lower. What does LO1, LO2 etc. refer to?
I named them L-HEOG etc. but still did not read...
