### ISSUE TITLE
Import .EEG file error message unrecognized function or variable 'chan_names'

### ISSUE THREAD

**Issue by AdamDuongIt** [sccn/neuroscanio#4]
Hello,

I am trying to import from EEG file on eeglab with error
`EEGLAB error in function loadeeg() at line 253:
Unrecognized function or variable 'chan_names'`

Please find the .eeg file in the attachment
[FA007K9P.EEG.zip](https://github.com/sccn/neuroscanio/files/10833613/FA007K9P.EEG.zip)

Regards,
Adam

**Comment by arnodelorme** [comment]
This is a Nihon Kodhen file not a Neuroscan file. It requires using BIOSIG to import and installing mexSLOAD which is not trivial. https://sourceforge.net/p/biosig/wiki/FAQ/
